# Generated by Django 5.0.1 on 2024-04-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarelist',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
